[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
